@extends("layouts.landing")@section("title", "Patarimai Tėvams")@section("content")
                            <p style=""></p>
    <div><img src="https://mokyklelepasaka.lt/uploads/page-uploads/23-JDsGVesBcN6q58GW.webp" class="responsive" alt="skritulys.jpg" style="width: 411px; height: 411px; object-fit: cover; object-position: 50% 50%;">
                <div id="comp-kkpbjx06" class="_2bafp" data-testid="richTextElement"><h1 class="font_0" style="font-size: 50px;"><span style="font-size:50px;"><span style="color:#54efd1">Patarimai dvikalbių vaikų tėvams </span></span></h1>

                    </div>
    </div>

                <h1>
        <div id="comp-kocrbvry" class="_2bafp" data-testid="richTextElement" style="margin: 0px 0px 23px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: none; overflow-wrap: break-word; position: relative; left: 0px; grid-area: 1 / 1 / 2 / 2; place-self: start; height: auto;  font-size: 10px; font-weight: 400;">
            <h1 class="font_0" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; font-size: 25px; line-height: normal; color: rgb(var(--color_15));">
                <span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-size: 34px;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: playfairdisplay-bold, &quot;playfair display&quot;, serif;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: rgb(84, 239, 209);">+&nbsp;</span></span></span><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">Gyva kalba</span>
            </h1></div>

    </h1><p></p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal; ">
        Viešojoje erdvėje dažnai pasirodo „griežtosios“ kalbotyros stovyklos lingvistų nuomonės, kad būtina visur ir
        visada kalbėti taisyklinga lietuvių kalba, nepažeisti bendrinės kalbos normų (taisyklių), nes kitu atveju,
        lietuvių kalbai gresia išnykimas, todėl draudžia svetimybių ir kitokių nelietuviškų žodžių vartojimą.</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        Tačiau kasdienė kalba gyvena visai kitaip. Ji gyva, spalvota, įdomi ir labai dažnai netikėta, sugalvojanti
        įvairiausių žodžių, kurie skamba juokingai, liūdnai ir rimtai. Ši kalba kiekvieną dieną mus lydi kaip draugė,
        kuri padeda padaryti viską: ryte pasisveikinti su kaimynu, kepyklėlėje nusipirkti karštos kakavos ir šviežią
        bandelę su marcipanu, internetu užsisakyti knygų, bendrauti ir dalytis savo požiūriu, skaityti šį straipsnį. Ir
        labai dažnai ši kalba būna netaisyklinga: žodžiai sukirčiuoti ne pagal taisykles (čia galima prisiminti
        ankstesnį straipsnį apie tarmes: skirtingi regionai turi jiems būdingą kirčiavimo požymį, pvz., vieni kirčius
        atitraukia į žodžio priekį, kiti ilgina galūnes), vartojama daug svetimybių, žargonų.</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        Ročesterio universiteto (JAV) lingvistė Solveiga Armoškaitė teigia, kad kalbos vartotojai ieško guvios kalbos
        variantų, o kalbos politikos modelis, kuris nurodo, kas yra taisyklinga, o kas – netaisyklinga kalba, yra
        pasenęs, nepriimtinas šiuolaikiniam kalbos vartotojui. Lingvistė kelia klausimą: kaip žmonės norės mokytis
        kalbos, kai vis pabrėžiamos klaidos? Jie praranda susidomėjimą mokytis kalbos, o gimtakalbiai apie save galvoja,
        kad jie nemoka kalbėti sava kalba. Padorus kalbos specialistas ir geras pedagogas pabrėš tai, kas daroma gerai,
        lavins kūrybiškumą, pagirs už netikėtą metaforą. Todėl kalbos prestižui didžiausia įtaka yra daroma mokykloje,
        kai jauni žmonės geba greitai įsisavinti kalbą.</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        Taigi diskutuojant apie kalbos taisyklingumą, matyt, verta sutikti su tuo, kad taisyklinga kalba yra kalbos
        etiketo ir registro klausimas (kur ir ką galima vartoti), o tai, kad bendraudami ar susitikdami su bičiuliais
        žmonės kirčiuoja netaisyklingai, vartoja svetimžodžius, barbarizmus, nepadaro jų prasčiau mokančių lietuvių
        kalbą, priešingai, tai parodo, kaip individas suvokia ir kurią kalbą.&nbsp;&nbsp;</p><p></p><h1></h1>
    <h1 class="font_0" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; font-size: 25px; line-height: normal;">
        <span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-size: 34px;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: playfairdisplay-bold, &quot;playfair display&quot;, serif;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: rgb(84, 239, 209);">+&nbsp;</span></span></span><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">Tikros tėvų patirtys&nbsp;</span>
    </h1><p></p>
        <p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; font-weight: 400; font-size: 18px; line-height: normal; letter-spacing: normal;">
            Organizuojame seminarus dvikalbystės tema, kuriuose dalijamasi ne tik mokslininkų tyrimais. Čia mielai apie
            asmeninę patirtį diskutuoja dvikalbių vaikų tėvai ir globėjai. Dalinamės keliomis istorijomis, kurios
            puikiai iliustruoja lingvistų tyrimų išvadas bei praktinius patarimus:</p>
        <ul class="font_8" style="margin: 0px 0px 0px 0.5em; padding: 0px 0px 0px 1.3em; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; list-style-position: initial; list-style-image: initial; pointer-events: auto; font-weight: 400; font-size: 18px; line-height: normal; letter-spacing: normal;">
            <li style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-style: inherit; font-weight: inherit; line-height: inherit;">
                <p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; line-height: normal; color: rgb(var(--color_15)); letter-spacing: normal;">
                    „Sūnus vienu metu mane ignoravo. Aš su juo kalbėdavau lietuviškai, o jis man atsakydavo tik
                    angliškai. Tačiau šis etapas praėjo ir dabar jau su manimi kalba lietuviškai. Džiaugiuosi, kad
                    nepasidaviau.“</p></li>
            <li style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-style: inherit; font-weight: inherit; line-height: inherit;">
                <p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; line-height: normal; color: rgb(var(--color_15)); letter-spacing: normal;">
                    „Grįžus į Lietuvą atostogų, vaikus užrašau į dienos stovyklą arba darželį. Iš karto pastebiu
                    pagerėjimą.“</p></li>
            <li style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-style: inherit; font-weight: inherit; line-height: inherit;">
                <p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; line-height: normal; color: rgb(var(--color_15)); letter-spacing: normal;">
                    „Nesistengiu turėti aukštų lūkesčių: žinau. kad mano sūnūs niekada tobulai nešnekės lietuviškai.
                    Tačiau noriu, kad jie mokėtų bent minimalias lietuviškas frazes, susikalbėtų su seneliais. Turint
                    mažesnius tikslus, lengviau eiti šiuo keliu.“</p></li>
            <li style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-style: inherit; font-weight: inherit; line-height: inherit;">
                <p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; line-height: normal; color: rgb(var(--color_15)); letter-spacing: normal;">
                    „Ne visuomet pavyksta su sūnumis šnekėti lietuviškai, nes šeimoje daugiausia bendraujame švediškai.
                    Tačiau yra kai kurie momentai, kai šneku tik lietuviškai: tai tam tikri mūsų ritualai arba žaidimai
                    kartu su manimi.“</p></li>
            <li style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-style: inherit; font-weight: inherit; line-height: inherit;">
                <p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; line-height: normal; color: rgb(var(--color_15)); letter-spacing: normal;">
                    „Kas savaitę darome vaizdo skambutį su mano draugės vaikais iš Lietuvos. Mano ir jos vaikai iki 15
                    minučių kalbasi apie savo naujus daiktus, rodo vienas kitam žaislus. Taip jiems didesnė motyvacija
                    kalbėti lietuviškai.“</p></li>
            <li style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-style: inherit; font-weight: inherit; line-height: inherit;">
                <p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; line-height: normal; color: rgb(var(--color_15)); letter-spacing: normal;">
                    „Eidamos į mokyklą pasikartojame žodžius, kuriuos mokėmės Pasakos pamokose. Pavyzdžiui, jei mokėmės
                    apie orą ir dangaus kūnų pavadinimus, tai aptariame, ką matome danguje.“</p></li>
            <li style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-style: inherit; font-weight: inherit; line-height: inherit;">
                <p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; line-height: normal; color: rgb(var(--color_15)); letter-spacing: normal;">
                    „Kartu su vaikais dažnai deklamuojame savo mėgstamus eilėraštukus ir dainuojame daineles, jie taip
                    puikiai įsimena žodžius.“</p></li>
            <li style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-style: inherit; font-weight: inherit; line-height: inherit;">
                <p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; line-height: normal; color: rgb(var(--color_15)); letter-spacing: normal;">
                    „Kai gimė sūnus, pasidaviau, nors iš pradžių šnekėdavau su juo lietuviškai, kadangi jis mane
                    ignoravo, perėjau prie prancūzų kalbos. Tad lietuvių kalbos taip ir neišmoko gerai. Tačiau gimus
                    dvynukėms, jo sesėms, nusprendžiau nepasiduoti ir su jomis kalbu tik lietuviškai. Mergaitėms sekasi
                    gerai, o kas smagiausia, pastebėjau, kad ir sūnus matydamas mus besikalbančias lietuviškai, pats
                    pradeda stengtis kalbėti šia kalba ir turi didesnę motyvaciją.“</p></li>
        </ul>
        <p></p><h1></h1><h1 class="font_0" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; font-size: 25px; line-height: normal;">
        <span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-size: 34px;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: playfairdisplay-bold, &quot;playfair display&quot;, serif;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: rgb(84, 239, 209);">+&nbsp;</span></span></span><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">Nesisarmatyk – didziuokis savą tapatybi!</span>
    </h1><p></p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        Visi puikiai žinome, kiek daug dialektų turi anglų kalba. O kaip su lietuvių kalbos tarme?</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        <span class="wixGuard" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">​</span>
    </p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        Dažnai manone, kad čia įvairovės nėra. Pavyzdžiui, esame įsitikinę, kad yra tik vienas taisyklingas žodis
        pasakyti svogūnas, o tas, kuris sako cibulis — lietuvių kalbos neišmano.</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        Visgi klystame! Lietuviai skirtinguose regionuose kalba nevienodai (kaip ir daugelyje kitų pasaulio šalių),
        pvz., vilniškių tarmėje sakoma ūtaryt vietoje pasikalbėti, o žemaičių krašte sako roukoutes. Be to, kiekvieno
        regiono tarmės klasifikuojamos dar smulkiau, taigi lietuviai turi ypač gražias ir archajiškas regionų kalbas, o
        bendrinė kalba reikalinga oficialiems dokumentams, viešajai kalbai ir informacijai. Visgi bendraudami su
        draugais, artimaisiais, kaimynais vartojame įvairią leksiką: bendrinę kalbą, tarmes, žargonus, svetimybes.</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        Regionai, kuriuose paplitusi norminė kalba, į tarmiškus žiūri ne itin teigiamai. Toks žmogus gali atrodyti kaip
        svetimšalis, kuris nemoka lietuvių bendrinės kalbos. Tačiau 2014 metais lietuvių kalbininkai atliko tyrimą
        (Rinkauskienė R., Salienė V.), kuriame aiškinosi, koks yra jaunimo požiūris į kalbėjimą tarmiškai. Šio tyrimo
        išvados džiuginančios, dauguma jaunų žmonių sako, kad tarmiškai kalbėti įdomu, linksma, taip nepasimiršta „sava“
        kalba. Jie nesigėdija tarmės, priešingai, gerbia ir vartoja kalbą, kuri, kaip jie įvardija, yra įgimta.</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        Taigi požiūris į kalbančius tarmiškai keičiasi, o svarbiausia, taip išsaugoma tapatybė. Kalbininkas Aleksas
        Girdenis teigė, kad „Tėvynė prasideda nuo gimtojo kiemo, gimtoji kalba yra ta, kurią gauname iš Motinos...
        Mokykis, jei nori, dieną naktį – jokia kalba netaps tokia kaip gimtoji tarmė.“</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        <span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: &quot;playfair display&quot;, serif;">Pasakoje</span>&nbsp;išeivius
        lietuvius taip pat siekiame supažindinti su lietuvių kalbos įvairove, gražiomis tarmėmis, o tai yra neatsiejama
        kultūros ir tapatybės dalis.</p><p></p><h1></h1><h1></h1><h1 class="font_0" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; font-size: 25px; line-height: normal;">
        <span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-size: 34px;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: playfairdisplay-bold, &quot;playfair display&quot;, serif;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: rgb(84, 239, 209);">+&nbsp;</span></span></span><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">Kas yra daugiakalbystė?</span>
    </h1><p></p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        Kalbėdami apie daugiakalbystės ir dvikalbystės apibrėžimus, dažnai susiduriame su keliais mitais. Keli jų:</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        &nbsp;</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        <span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; text-decoration-line: underline;">Daugiakalbis&nbsp;<span style="font-family: din-next-w01-light, din-next-w02-light, din-next-w10-light, sans-serif;">—&nbsp;</span>tai žmogus, mokantis daugiau nei vieną kalbą.</span></p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        Tai nėra tikslus daugiakalbystės apibrėžimas. Dauguma lingvistų daugiakalbystę skiria nuo gebėjimo kalbėti
        keliomis užsienio kalbomis. Kitaip tariant, jei žmogus kalba dviem kalbomis, kurias pradėjo įsisavinti
        vaikystėje (maždaug iki 3 m.), jis laikomas dvikalbiu. Jei išmokstama kalbų vėliau, jis nėra dvikalbis, o žmogus, mokantis kelias užsienio kalbas.</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        &nbsp;</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        <span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; text-decoration-line: underline;">Dvikalbis vaikas&nbsp;<span style="font-family: din-next-w01-light, din-next-w02-light, din-next-w10-light, sans-serif;">—&nbsp;</span>tik tas, kuris abi kalbas yra įsisavinęs ir kalba abiem kalbom vienodai gerai.</span>
    </p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        Tobulai subalansuotų dvikalbių realybėje tikrai yra, bet tai&nbsp;<span style="font-family: din-next-w01-light, din-next-w02-light, din-next-w10-light, sans-serif;">—</span>&nbsp;retenybė. Labai normalu, kai vaikas viena kalba
        kalba geriau nei kita. Taip pat labai dažnai viena kalba yra dominuojanti (aplinkos kalba), o kita&nbsp;<span style="font-family: din-next-w01-light, din-next-w02-light, din-next-w10-light, sans-serif;">—</span>&nbsp;mažumos
        kalba (vieno arba abiejų tėvų kalba). Todėl savaime supranta, kad vaikas geriau kalbės dominuojančia kalba.
        Svarbu ir tai, apie ką vyksta pokalbis. Pavyzdžiui, vaikas kalbėdamas apie buitį lengviau valdo silpnąją kalbą,
        bet kalbėdamas apie istorinius įvykius, kuriuos mokėsi mokykloje, rinksis dominuojančią kalbą. Galiausiai,
        dvikalbiui vaikui būdinga maišyti kelias kalbas sakinyje, tai vadinama <i>kodų kaita</i>.</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        &nbsp;</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        <span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; text-decoration-line: underline;">Dvikalbystė / Daugiakalbystė&nbsp;<span style="letter-spacing: 1px;">–&nbsp;</span>retas reiškinys.</span>
    </p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        Pasaulyje yra daugiau dvikalbių nei vienakalbių žmonių (Grosjean). Nepamirškite, kad yra šalių, kuriose yra
        kelios valstybinės kalbos, pavyzdžiui, Šveicarija, Kanada, bei šalių, kur yra keli dialektai, pavyzdžiui,
        mandarinų ir kantoniečių dialektai Kinijoje, baskų, katalonų dialektai Ispanijoje, nors pagrindinė kalba&nbsp;<span style="letter-spacing: 1px;">–</span>&nbsp;ispanų. Jungtinės Amerikos Valstijose 47 mln. gyventojų namuose vartoja kitą nei anglų kalbą (Bialystok &amp;
        Hakuta). Kalbų įvairovę puikiai vaizduoja&nbsp;<span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; text-decoration-line: underline;"><a href="https://www.ethnologue.com/guides/how-many-languages" target="_blank" rel="noopener" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; cursor: pointer; color: inherit;">šis kalbų žemėlapis</a></span>.
        Taigi nesijaudinkime, daugiakalbystė yra visiškai normalu!</p><p></p><h1></h1><h1 class="font_0" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; font-size: 25px; line-height: normal;">
        <span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-size: 34px;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: playfairdisplay-bold, &quot;playfair display&quot;, serif;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: rgb(84, 239, 209);">+&nbsp;</span></span></span><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">Lietuvių kalboje tiek daug mažybinių formų, ar tai gali sulėtinti mano vaiko kalbos vystymąsi?&nbsp;</span>
    </h1><p></p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        Gal geriau man vengti tokių žodžių kaip <i>mašinytė</i>, <i>katytė</i>, nes jis nesupras, kad tai mašina, katė ir
        ilgiau užtruks, kol išmoks šiuos žodžius?</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        Norime jus nuraminti. Jei jūs su vaiku nuo pat jo gimimo kalbate lietuviškai, mažybinės formos tikrai nesukels
        rūpesčių jam įsisavinant kalbą, atvirkščiai - tai netgi padės taisyklingai ištarti kai kurias frazes ir
        žodžius.</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        &nbsp;</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        Visų pirma, vaikai (ir suaugę) žodžius suskaido į mažesnes jų dalis: žodžio šaknį mašin- arba kat-, žodžio
        priesagą -yt-&nbsp; ir galūnę -ė. Vaikas ankstyvoje kalbos raidos stadijoje pirmenybę teikia žodžio
        šakniai (Eve V. Clark 2009). Ji nusako žodžio reikšmę. Taigi vaikas žino, kad <i>mašin-ą, mašin-ai, mašin-a, mašin-yt-ė, mašin-yt-ę</i> yra vienas ir tas pats žodis su skirtingomis galūnėmis ir priesagomis. Tos galūnės ir
        priesagos turi užkoduotą skirtingą gramatinę informaciją (angl.&nbsp;<span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-style: italic;">functional morphemes</span>).
    </p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        &nbsp;</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        O kaip greitai vaikai įsisavina ir pradeda taisyklingai vartoti priesagas ir galūnes? Tai priklauso nuo žodžio
        dalių semantinio sudėtingumo, dažnumo ir reguliarumo (Eve V. Clark 2009). Dažnesnės formos įsisavinamos
        greičiau. O lietuvių kalboje mažybinės formos yra labai dažnos! Ypač mamų ir tėčių kalboje, kai jie kalba su
        savo vaikučiais. Todėl vaikai jas įsisavina lengvai ir jas vartoja (juolab supranta) jau nuo pat mažų dienų.
        Pavyzdžiui, mano dukra gėlytę vadina <i>lyte</i>, sausainį&nbsp;<span style="letter-spacing: 1px;">–</span>&nbsp;<i>nukas</i>, o katę&nbsp;<span style="letter-spacing: 1px;">–</span>&nbsp;<i>katytė</i> arba <i>čiukas</i>.</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        &nbsp;</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        Pasak Inetos Dabašinskienės mažybinius žodelius vaikai vartoja tiek pat dažnai kiek paprastas formas.
        Mokslininkė taip pat pastebėjo, kad vaikai vartodami mažybines formas padaro mažiau klaidų parinkdami linksnių
        galūnes. Pavyzdžiui,&nbsp; <i>šuo</i> ir&nbsp; <i>sausainis</i> priklauso skirtingoms linksniuotėms, tačiau tiek <i>šuniukas</i>, tiek <i>sausainiukas</i> turi tos pačios (pirmos) linksniuotės galūnes. Taigi vaikui vartojant mažybinę
        formą reikia žinoti ir mažiau vartojamų linksnių galūnių.</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        &nbsp;</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        Mažybinės formos žodžius lengviau kirčiuoti&nbsp;<span style="letter-spacing: 1px;">–</span>&nbsp;tokiuose žodžiuose kirtis beveik visuomet yra ant mažybinės
        priesagos, pvz., <i>mašin-ytė, kat-ytė</i>. Tad vaikui nereikia galvoti, kur dėti kirtį.</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        Išvada&nbsp;<span style="letter-spacing: 1px;">–</span>&nbsp;nevenkite mažybinių formų bendraudami su vaikais! Tegyvuoja kačiukai, šuniukai, vaikučiai ir
        mamytės!</p><p></p><h1></h1>
    <h1 class="font_0" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; font-size: 25px; line-height: normal;">
        <span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-size: 34px;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: playfairdisplay-bold, &quot;playfair display&quot;, serif;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: rgb(84, 239, 209);">+&nbsp;</span></span></span><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">Kodėl mano trimetis vaikas trumpina ilgesnius žodžius? Kodėl mano dvimetė dukra dar nekalba ilgais sakiniais?</span>
    </h1>
        <p></p>
        <p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; font-weight: 400; font-size: 18px; line-height: normal; letter-spacing: normal;">
            Neretai dvikalbių vaikų tėvai dėl to jaudinasi. Norime jus nuraminti, kad tai yra normalu. Dalinamės
            vaiko kalbos raidos gairėmis, kurias adaptavome pagal lingvistės Barbara Zuer Pearson lentelę (<span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-style: italic;">Raising a Bilingual Child</span>&nbsp;2008).
        </p>
        <p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; font-weight: 400; font-size: 18px; line-height: normal; letter-spacing: normal;">
            &nbsp;</p>
        <p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; font-weight: 400; font-size: 18px; line-height: normal; letter-spacing: normal;">
            16<span style="letter-spacing: 1px;">–</span>18 mėn. vaikas: geba suprasti ir pasakyti pavienius žodžius. Berniukai žino nuo 13&nbsp; iki
            420 žodžių, o&nbsp; mergaitės&nbsp;<span style="letter-spacing: 1px;">–</span>nuo 17 iki 475. Jei vaikas daugiau nei 18 mėn. ir jis nesugeba pasakyti nė vieno žodžio&nbsp;<span style="letter-spacing: 1px;">–</span>&nbsp;nesijaudinkite. Tačiau reikėtų sunerimti, jei jis vis dar jų nesupranta.</p>
        <p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; font-weight: 400; font-size: 18px; line-height: normal; letter-spacing: normal;">
            &nbsp;</p>
        <p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; font-weight: 400; font-size: 18px; line-height: normal; letter-spacing: normal;">
            24 mėn. vaikas: geba suprasti daugelį sakinių ir frazių. Sugeba pasakyti sakinius iš
            dviejų žodžių, pvz., n<i>oliu niam niam</i> (noriu valgyt), <i>duok bubu</i> (duok mašinytę). Dauguma vaikų pradeda kalbėti
            tokiomis paprastomis žodžių kombinacijomis iki 26 mėn.</p>
        <p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; font-weight: 400; font-size: 18px; line-height: normal; letter-spacing: normal;">
            &nbsp;</p>
        <p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; font-weight: 400; font-size: 18px; line-height: normal; letter-spacing: normal;">
            36 mėn. vaikas: geba suprasti daugelį frazių ir sakinių, palaipsniui pradeda suvokti abstrakčių
            žodžių reikšmę.&nbsp; Sugeba kalbėti paprastais sakiniais apie įvykius, vykstančius čia ir dabar. Vaiko kalba
            ir ištartos frazės labiau suprantamos nei dvimečio vaiko. Palaipsniui pradeda dalyvauti dialoge ir
            vysto pokalbį.</p>
        <p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; font-weight: 400; font-size: 18px; line-height: normal; letter-spacing: normal;">
            &nbsp;</p>
        <p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; font-weight: 400; font-size: 18px; line-height: normal; letter-spacing: normal;">
            5 metų vaikas: geba gerai suprasti aplinkinių kalbą, taip pat kalbėti sudėtiniais sakiniais, pvz., <i>aš nenoriu
            šios sriubos, nes ji man neskani</i>. Sėkmingai dalyvauja pokalbyje.</p>
        <p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; font-weight: 400; font-size: 18px; line-height: normal; letter-spacing: normal;">
            &nbsp;</p>
        <p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; font-weight: 400; font-size: 18px; line-height: normal; letter-spacing: normal;">
            Tikimės šios gairės jums padės nusiraminti ir parodys, kada tikrai reikėtų kreiptis į specialistą.</p>
        <p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; font-weight: 400; font-size: 18px; line-height: normal; letter-spacing: normal;">
            &nbsp;</p>
        <p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; font-weight: 400; font-size: 18px; line-height: normal; letter-spacing: normal;">
            Dar norime priminti, kad dvikalbių ir vienakalbių vaikų raida yra tokia pati. Tačiau reikia nepamiršti, kad
            dvikalbio situacijoje viena iš kalbų dažniausiai yra dominuojanti, o kita&nbsp;<span style="letter-spacing: 1px;">–&nbsp;</span>nuslopinta, todėl norėdami suprasti, ar jūsų vaikas neturi kalbos sutrikimų, reikia atkreipti dėmesį, kaip jis kalba abejomis
            kalbomis.</p>
        <p></p><h1></h1><h1 class="font_0" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; font-size: 25px; line-height: normal;">
        <span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-size: 34px;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: playfairdisplay-bold, &quot;playfair display&quot;, serif;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: rgb(84, 239, 209);">+&nbsp;</span></span></span><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">Ar mano požiūris į lietuvių kalbą ir lietuvių kultūrą turi reikšmės vaiko motyvacijai kalbėti lietuviškai?</span>
    </h1><p></p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        Žinoma! Jūs, kaip tėvai ar globėjai, atliekate svarbiausią vaidmenį vaiko dvikalbystės kelionėje. Kuo daugiau
        Lietuva jūsų namuose asocijuosis su geromis ir linksmomis emocijomis, teigiamomis akimirkomis bei patraukliomis
        istorijomis, tuo vaikas turės didesnį norą kalbėti lietuviškai. Lietuvių kalba turi tapti prestižo
        kalba jūsų namuose. Kaip tai pasiekti?</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        &nbsp;</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        - Didžiuokitės savo kultūra ir istorija, tai parodykite veiksmais: švęskite Lietuvos valstybines šventes, į jas pakvieskite ne tik draugus lietuvius, bet ir užsieniečius&nbsp;<span style="font-family: din-next-w01-light, din-next-w02-light, din-next-w10-light, sans-serif;">—</span>&nbsp;taip vaikai matys, kad jūs nebijote džiaugtis
        savo šalimi;</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        <span class="wixGuard" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">​</span>
    </p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        - Namuose turėkite meno kūrinių ir kitų daiktų iš Lietuvos. Taip arčiau turėsite Lietuvą ir jos kultūrą;</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        <span class="wixGuard" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">​</span>
    </p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        - Klausykitės šiuolaikinės lietuviškos muzikos, žiūrėkite lietuviškas laidas bei filmus kartu su vaikais;</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        &nbsp;</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        - Turėkite kuo daugiau lietuviškų knygų! Šiuolaikinės knygos yra itin patrauklios mažiesiems
        lietuviams;</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        <span class="wixGuard" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">​</span>
    </p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        - Jei nepavyksta namuose visada klabėti lietuviškai, vartokite tą kalbą, kai su vaiku darote ką
        nors smagaus: einate į parduotuvę pirkti naujų žaislų ar valgyti ledų, žaidžiate žaidimą ar
        skaitote juokingą istoriją;</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        <span class="wixGuard" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">​</span>
    </p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        - Kalbėkite lietuviškai, kai giriate savo vaikus, didžiuojatės ir džiaugiatės jais;</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        &nbsp;</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        - Įsivaizduokite, kad jūsų vaiko mėgstamiausias žaislas (o gal naminis gyvūnas) kalba tik lietuviškai ir su juo
        kalbėkite tik lietuviškai.</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        <span class="wixGuard" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">​</span>
    </p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        - Vakarais prieš miegą linksmai ir žaismingai papasakokite Lietuvos istoriją.</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        &nbsp;</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        Nesijaudinkite, jei ne visuomet pavyksta. Prisiminkite anglišką frazę, kuri kartojama knygose tėvams apie vaikų
        auklėjimą:<span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-style: italic;">&nbsp;be consistent, but not rigid</span>.
        Laikykitės savo taisyklių ir susitarimų, bet būkite lankstūs ir nebijokite kartais jas sulaužyti.</p><p></p>
    <h1></h1><h1 class="font_0" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; font-size: 25px; line-height: normal;">
        <span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-size: 34px;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: playfairdisplay-bold, &quot;playfair display&quot;, serif;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: rgb(84, 239, 209);">+&nbsp;</span></span></span><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">Mano vaikui dveji metukai ir jis dar nekalba lietuviškai, tik savo kažkokia keista, nesuprantama kalba. Ar tai yra dėl to, kad jis auga dvikalbėje aplinkoje?</span>
    </h1><p></p>
    <div id="comp-kl9pagmm" class="_2bafp" data-testid="richTextElement" style="margin: 0px 0px 26px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: none; overflow-wrap: break-word; position: relative; left: 14px; grid-area: 21 / 1 / 22 / 2; place-self: start; height: auto; font-size: 10px; letter-spacing: normal;">
        <p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; font-size: 18px; line-height: normal; color: rgb(var(--color_15)); letter-spacing: normal;">Nereikėtų jaudintis, jei tokio amžiaus vaikas dar nekalba. Tai tikrai nėra susiję su tuo, kad jo
            aplinkoje kalbama keliomis kalbomis. Dažnai vienakalbiai tokio amžiaus vaikučiai dar nekalba.</p>
        <p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; font-size: 18px; line-height: normal; color: rgb(var(--color_15)); letter-spacing: normal;">
            &nbsp;</p>
        <p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; font-size: 18px; line-height: normal; color: rgb(var(--color_15)); letter-spacing: normal;">Jei vaikas kalba savo kalba, vadinasi jis jau kalba! Tad jaudintis nereikėtų. Kas yra vaiko nesuprantama kalba? Tai supaprastina lietuvių ar kita kalba, o gal kelių kalbų mišinys. Kodėl
            dauguma vaikų taip kalba? Vaikams ištarti daugiaskiemenius žodžius ir kai kuriuos garsus yra per sunku ir
            per daug sudėtinga, jie nėra tam pasiruošę. Todėl dažnai žodžius supaprastina iki dviejų skiemenų, priebalsių, balsių, pavyzdžiui, senelis tampa <i>neli</i>. Taip pat dvimečiai
            linkę vartoti tik vieną žodžio skiemenį ir jį kelis kartus pakartoti, pvz., Petras tampa <i>pepe</i>, Barbora&nbsp;<span style="font-family: din-next-w01-light, din-next-w02-light, din-next-w10-light, sans-serif;">—&nbsp;</span><i>baba</i>, o peilis&nbsp;<span style="font-family: din-next-w01-light, din-next-w02-light, din-next-w10-light, sans-serif;">—</span>&nbsp;<i>pipi</i>. Dėl tokių supaprastinimų vienas vaikučio žodis gali turėti net kelias reikšmes: <i>pipi</i> gali reikšti ir pirtį, ir peilį. Šis reiškinys vadinamas asimiliacija&nbsp;<span style="letter-spacing: 1px;">–</span>&nbsp;sudėtingesni garsai žodyje
            pakeičiami į šalia esančius garsus.</p>
        <p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; font-size: 18px; line-height: normal; color: rgb(var(--color_15)); letter-spacing: normal;">
            &nbsp;</p>
        <p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; font-size: 18px; line-height: normal; color: rgb(var(--color_15)); letter-spacing: normal;">
            Taigi vaikų nesuprantama arba nesąmoninga kalba iš tikrųjų yra supaprastinta kalba, kurią
            vaikas girdi savo aplinkoje. Tad nesijaudinkite ir dar daugiau bendraukite su savo vaiku lietuviškai.</p>
        <div><br></div>
    </div><p></p>
    <h1>
        <div id="comp-kl0v4vsw" class="_2bafp" data-testid="richTextElement" style="margin: 0px 0px 27px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: none; overflow-wrap: break-word; position: relative; left: 1px; grid-area: 23 / 1 / 24 / 2; place-self: start; height: auto;  font-size: 10px; font-weight: 400;">
            <h1 class="font_0" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; font-size: 25px; line-height: normal; color: rgb(var(--color_15));">
                <span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-size: 34px;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: playfairdisplay-bold, &quot;playfair display&quot;, serif;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: rgb(84, 239, 209);">+&nbsp;</span></span></span><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">Bijau su vaiku šnekėti lietuviškai, o kas, jei jis neišmoks anglų kalbos?</span>
            </h1>
            <div>
                <span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><br></span>
            </div>
        </div>
        <div id="comp-kl0v50gh" class="_2bafp" data-testid="richTextElement" style="margin: 0px 0px 40px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: none; overflow-wrap: break-word; position: relative; left: 1px; grid-area: 24 / 1 / 25 / 2; place-self: start; height: auto;  font-size: 10px; font-weight: 400;"></div>
    </h1><p></p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;"><span style="font-family: din-next-w01-light, din-next-w02-light, din-next-w10-light, sans-serif;">„</span>Logopedas patarė su vaiku šnekėti tik angliškai<span style="font-family: din-next-w01-light, din-next-w02-light, din-next-w10-light, sans-serif;">“</span>&nbsp;<span style="font-family: din-next-w01-light, din-next-w02-light, din-next-w10-light, sans-serif;">—&nbsp;</span>tokiomis problemomis dalinasi Pasakos tėvai ir globėjai.</p>
    <p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        &nbsp;</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        Nesijaudinkite, jūsų vaikas tikrai puikiai šnekės angliškai (ar kita jūsų aplinkoje vartojama kalba). Logopedai,
        išmanantys vaiko kalbos raidą, tikrai tokių patarimų neturėtų duoti.</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        Dvikalbėse arba daugiakalbėse situacijose dažniausiai lietuvių kalba yra mažumos kalba (ja kalba tik vaiko tėvai
        arba vienas iš tėvų). Tokioje situacijoje anglų ar kitos kalbos dažniausiai būna dominuojančios kalbos (ją
        vaikas girdi už namų ribų: darželyje, mokykloje, tarp draugų, parduotuvėje). Dominuojančią kalbą vaikas puikiai
        įsisavins net jei ją aktyviai pradės vartoti ir vėliau, pavyzdžiui, kai eis į darželį ar mokyklą. Vaikai puikiai
        sugeba įsisavinti kelias kalbas vienu metu. Deja, dominuojanti kalba, ypač mokyklinukų atveju, palaipsniui
        užgožia lietuvių kalbą. Tad labai svarbu jau nuo pat kūdikystės šnekėti su vaiku tik lietuviškai ir stengtis to
        susitarimo šeimoje laikytis.</p><p></p><h1></h1><h1 class="font_0" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; font-size: 25px; line-height: normal;">
        <span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-size: 34px;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: playfairdisplay-bold, &quot;playfair display&quot;, serif;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: rgb(84, 239, 209);">+&nbsp;</span></span></span><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">Su vaiku kalbu lietuviškai, bet jis vis tiek su manimi kalba angliškai, ką daryti?</span>
    </h1><p></p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        Dažnai tėvai kreipiasi į mus šiuo klausimu. Dalinamės keliais patarimais. Jei vaikas jums sako:&nbsp;<span style="font-family: din-next-w01-light, din-next-w02-light, din-next-w10-light, sans-serif;">„</span>Mommy water!<span style="font-family: din-next-w01-light, din-next-w02-light, din-next-w10-light, sans-serif;">“</span>&nbsp;Tokiu atveju:</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        - tęskite vaiko pradėtą dialogą gimtąja kalba:&nbsp;<span style="font-family: din-next-w01-light, din-next-w02-light, din-next-w10-light, sans-serif;">„</span>aha, ir aš esu ištroškusi, einame atsigerti vandens. Į
        kokį puodelį tau įpilti: žalią ar mėlyną?<span style="font-family: din-next-w01-light, din-next-w02-light, din-next-w10-light, sans-serif;">“</span>&nbsp;<span style="font-family: din-next-w01-light, din-next-w02-light, din-next-w10-light, sans-serif;">—</span>&nbsp;tai turėtų paskatinti vaiką atsakyti lietuviškai (nebūtinai iš
        karto);</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        - papasakokite vaikui, kaip jūs jaučiatės, kai vaikas kalba lietuviškai:&nbsp;<span style="font-family: din-next-w01-light, din-next-w02-light, din-next-w10-light, sans-serif;">„</span>aš tave geriau suprantu, kai tu kalbi
        lietuviškai<span style="font-family: din-next-w01-light, din-next-w02-light, din-next-w10-light, sans-serif;">“</span>,&nbsp;<span style="font-family: din-next-w01-light, din-next-w02-light, din-next-w10-light, sans-serif;">„</span>man taip gera, kai tu man atsakai lietuviškai<span style="font-family: din-next-w01-light, din-next-w02-light, din-next-w10-light, sans-serif;">“</span>;</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        - jei jūsų vaikas vartoja lietuviškus žodžius su klaidomis arba sakiniuose maišo kelias kalbas,
        nepertraukinėkite, netaisykite, nekritikuokite. Geriau tęskite pokalbį stengdamiesi į savo
        atsakymą įtraukti vaiko ištartas frazes be klaidų. Jie mokosi iš jūsų!&nbsp;</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        - nebauskite ir nekritikuokite vaiko, jei nekalba su jumis lietuviškai:&nbsp;<span style="font-family: din-next-w01-light, din-next-w02-light, din-next-w10-light, sans-serif;">„</span>koks dar water, vanduo!<span style="font-family: din-next-w01-light, din-next-w02-light, din-next-w10-light, sans-serif;">“</span>,&nbsp;<span style="font-family: din-next-w01-light, din-next-w02-light, din-next-w10-light, sans-serif;">„</span>o ką,
        lietuviškai negali paprašyti?<span style="font-family: din-next-w01-light, din-next-w02-light, din-next-w10-light, sans-serif;">“</span>.</p><p></p>
    <h1>
        <div id="comp-kkpdbgyr" class="_2bafp" data-testid="richTextElement" style="margin: 0px 0px 20px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: none; overflow-wrap: break-word; position: relative; left: 10px; grid-area: 29 / 1 / 30 / 2; place-self: start; width: 391px; height: auto;  font-size: 10px; font-weight: 400;">
            <h1 class="font_0" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; font-size: 25px; line-height: normal; color: rgb(var(--color_15));">
                <span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-size: 34px;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: playfairdisplay-bold, &quot;playfair display&quot;, serif;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: rgb(84, 239, 209);">+&nbsp;</span></span></span>Motyvuokite
                ir džiaukitės kartu</h1>
            <div><br></div>
        </div>
        <div id="comp-kkpdbgz2" class="_2bafp" data-testid="richTextElement" style="margin: 0px 0px 37px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: none; overflow-wrap: break-word; position: relative; left: 10px; grid-area: 30 / 1 / 31 / 2; place-self: start; width: 805px; height: auto;  font-size: 10px; font-weight: 400;"></div>
    </h1><p><span style="   letter-spacing: normal;">Labai svarbu, kad vaikas džiaugtųsi kiekvienu, net ir mažu, savo&nbsp;<span style="font-family: din-next-w01-light, din-next-w02-light, din-next-w10-light, sans-serif;">„</span>laimėjimu<span style="font-family: din-next-w01-light, din-next-w02-light, din-next-w10-light, sans-serif;">“</span>. Pagirkite ir kartu&nbsp;švęskite dėl<span style="font-family: din-next-w01-light, din-next-w02-light, din-next-w10-light, sans-serif;">&nbsp;</span>naujų išmoktų žodžių arba perskaitytos lietuviškos knygos. Išduosim paslaptį&nbsp;<span style="font-family: din-next-w01-light, din-next-w02-light, din-next-w10-light, sans-serif;">—&nbsp;</span>lipdukai kartais daro stebuklus!&nbsp;</span>
    </p><h1></h1><h1 class="font_0" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; font-size: 25px; line-height: normal;">
        <span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-size: 34px;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; font-family: playfairdisplay-bold, &quot;playfair display&quot;, serif;"><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; color: rgb(84, 239, 209);">+&nbsp;</span></span></span><span style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">Kaip paskatinti vaiką daugiau kalbėti lietuviškai?</span>
    </h1><p></p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        Kuo daugiau vaikas girdi lietuvių kalbą, tuo didesnė tikimybė, kad jis pradės geriau kalbėti lietuviškai. Visgi
        neužtenka tik girdėti&nbsp;<span style="letter-spacing: 1px;">–</span>&nbsp;vaikai geriausiai mokosi kalbų per bendravimą. Mūsų patarimai:</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        Kai skaitote lietuvišką knygą vaikams, bendraukite ir įtraukite juos į pasakojimą:&nbsp;<span style="font-family: din-next-w01-light, din-next-w02-light, din-next-w10-light, sans-serif;">„</span>kokius piešinėlius matai? Ką
        čia daro karvė? O kaip manai, ką dabar pasakys lapiukas?<span style="font-family: din-next-w01-light, din-next-w02-light, din-next-w10-light, sans-serif;">“</span></p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        Kai gaminate pusryčius, pasikvieskite vaikus į pagalbą! Kalbėkite, ką darote, kokius maisto produktus
        naudojate.</p><p class="font_8" style="margin: 0px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; pointer-events: auto; line-height: normal; letter-spacing: normal;">
        Kai žiūrite lietuviškus filmukus, žiūrėkite kartu ir aptarkite herojų veiksmus, išvaizdą, siužetą.</p><p></p><h1 style="text-align: center; color:#54efd1"> Sėkmės!</h1>                        @endsection